apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS inventory (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      stock INTEGER NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO inventory (name, stock) VALUES
    ('りんご', 100),
    ('バナナ', 150),
    ('みかん', 80),
    ('ぶどう', 200),
    ('パイナップル', 60),
    ('もも', 90),
    ('すいか', 40),
    ('メロン', 70),
    ('レモン', 120),
    ('キウイ', 110);
