apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: default
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS messages (
      id SERIAL PRIMARY KEY,
      content TEXT
    );

    INSERT INTO messages (content) VALUES
      ('こんにちは！'),
      ('VaultでDB接続成功！'),
      ('これはテストメッセージです。');
