apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tls
  template:
    metadata:
      labels:
        app: nginx-tls
    spec:
      serviceAccountName: vault
      volumes:
        - name: ssl
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 443
          volumeMounts:
            - name: ssl
              mountPath: /etc/nginx/ssl
              readOnly: false
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
        - name: vault-agent
          image: hashicorp/vault:1.15.4
          command: ["vault", "agent", "-config=/etc/vault/config/vault-agent-config.hcl"]
          volumeMounts:
            - name: ssl
              mountPath: /etc/nginx/ssl
            - name: nginx-conf
              mountPath: /etc/vault/config/vault-agent-config.hcl
              subPath: vault-agent-config.hcl
