apiVersion: v1
kind: Service
metadata:
  name: nginx-tls
  labels:
    app: nginx-tls
spec:
  type: NodePort
  selector:
    app: nginx-tls
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30443  # 任意のポート。Minikubeではこのポートにアクセス可能
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
